name: Build win-x64

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetches your code

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Change if using a different .NET version
          
      - name: Restore Dependencies
        run: dotnet restore src/cover-letter-template-adjuster.sln  # Adjust path if needed

      - name: Build Solution
        run: dotnet build src/cover-letter-template-adjuster.sln --configuration Release --no-restore

      - name: Publish with Visual Studio Publish Profile
        run: dotnet publish src/cover-letter-template-adjuster.csproj --configuration Release /p:PublishProfile=win-x64

      - name: Get Version from Tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Zip Published Files
        run: Compress-Archive -Path src/publish/* -DestinationPath clt-${{ env.VERSION }}.zip

      - name: Create GitHub Release and Upload Files
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          files: clt-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


